services:

  xchem-fff:
    build:
      context: xchem-fff
      dockerfile: Dockerfile
    platform: linux/amd64
    image: maxwinokan/jupyter-fff:latest
    ports:
      - "8888:8888"

  xchem-fff-syndirella:
    build:
      context: xchem-fff-syndirella
      dockerfile: Dockerfile
    platform: linux/amd64
    image: maxwinokan/jupyter-syndirella:latest
    ports:
      - "8888:8888"
